# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven - Eureka Server
      run: mvn -B package --file eureka-server/pom.xml
    - name: Build with Maven - Eureka Client
      run: mvn -B package --file eureka-client/pom.xml
    - name: Build with Maven - Feign Client
      run: mvn -B package --file feign-client/pom.xml
